http:
  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: "http://192.168.200.6:8123"
    
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.200.2:8006"
        passHostHeader: true
        serversTransport: insecure-transport

    truenas:
      loadBalancer:
        servers:
          - url: "http://192.168.200.15:80"

    unifi:
      loadBalancer:
        servers:
          - url: "https://unifi:8443"
        serversTransport: insecure-transport


  serversTransports:
    insecure-transport:
      insecureSkipVerify: true

tcp:
  services:
    postgres:
      loadBalancer:
        servers:
          - address: "3an-postgre-db:54321"
